### PR TITLE
Create de.js

### PR DESCRIPTION
**Pull request by elricco**
Translation of the english file with the help of @ansichtsache Kept some english stopwords

### CODE REVIEW

**Comment by adamchaboryk** [comment]
Thank you all so much for your contributions!! It's greatly appreciated. 😄 @elricco @skerbis @ansichtsache 

I'll merge this soon. Apologies for the slow reply, I just got back from a vacation.

**Comment by adamchaboryk** [comment]
Hi @elricco,

Can you please provide me translations for the following 3 strings?

````
 PANEL_DISMISS_BUTTON: 'Show %(dismissCount) dismissed warnings',
 DISMISS: 'Dismiss',
 DISMISSED: 'Dismissed warnings',
````

Thanks!!

**Comment by ansichtsache** [comment]
you are welcome!

PANEL_DISMISS_BUTTON: 'Zeige %(dismissCount) ignorierte Warnungen',
DISMISS: 'Ignorieren',
DISMISSED: 'Ignorierte Warnungen',

**Comment by adamchaboryk** [comment]
Danke!

**Pull request merged**
