### PR TITLE
Add typings

### PR DESCRIPTION
**Pull request by smncd**
Make Sa11y compatible with typescript projects by implementing type declarations, with very few changes to the project.

Changes:
- Add type declarations for Sa11y, Lang, and languages.
- Add index.js to project root from which we'll export the above functions. This is to make importing from node_modules easier.

### CODE REVIEW

**Comment by brianteeman** [comment]
This can't be correct, surely? as it removes reference to sa11y.js - or is it too early in the morning for me to be reading coe

**Comment by smncd** [comment]
> This can't be correct, surely? as it removes reference to sa11y.js - or is it too early in the morning for me to be reading coe

If you're referring to _main_ in package.json, sa11y.js is still referenced in, and exported from the added index.js file, along with helper functions.

**Comment by adamchaboryk** [comment]
Hi Simon, 

I've had some updates stashed away locally and have finally pushed them to another dev branch. Do you mind reviewing the branch (https://github.com/ryersondmp/sa11y/tree/v2.3.3-development) and submitting your pull request there? Apologies for the inconvenience!

## Summarized changes
- **New ruleset:** Detect inappropriate use subscript and superscript tags.
- **Removed ruleset:** Removed Twitter specific ruleset regarding infinite timelines. Recent changes to Twitter's embed API is now causing CORS issues with Sa11y.
- **Bug fix:** SessionStorage will be used as a fallback when LocalStorage is full.
- **New feature:** Clickable Page Outline panel. All of the headers that appear in the Page Outline link to the corresponding heading. For keyboard users, the Page Outline features a roving tabindex. Tab into the Page Outline, and then use up and down arrow keys to navigate between headings.
- **Refactoring:** Removed deprecated JS regarding Escape key logic.
**UI changes:** The Skip to Issue button is now more evident that it's a clickable button. Adjusted delay on tooltip helper.
- **Bug fix:** Hyperlinked images with a negative `tabindex` with alt text will not receive an annotation. Assumes that developer intentionally removed keyboard focus from clickable image.

I think @brianteeman will appreciate the removal of Twitter specific code!

**Comment by smncd** [comment]
@adamchaboryk No worries! I've pulled the changes into the typings branch and will change the target of the PR

**Pull request merged**
