### PR TITLE
lang file German corrected acrobat link

### PR DESCRIPTION
**Pull request by skerbis**
corrected acrobat link

### CODE REVIEW

**Comment by adamchaboryk** [comment]
Thanks @skerbis - i'll manually bring this fix over to my other development branch for version 3.0!

Would you please review or improve these machine translated strings?

```
    PAGE_ISSUES: 'Seitenprobleme',
    SKIP_TO_PAGE_ISSUES: 'Zu Seitenproblemen springen',
COLOUR_FILTER: 'Farbfilter',
    PROTANOPIA: 'Protanopie',
    DEUTERANOPIA: 'Deuteranopie',
    TRITANOPIA: 'Tritanopie',
    MONOCHROMACY: 'Monochromie',
    COLOUR_FILTER_MESSAGE: 'Suchen Sie nach Elementen, die schwer wahrnehmbar oder von anderen Farben zu unterscheiden sind.',
```

These are intended to be alt text for an icon that changes colour:
````
    RED_EYE: 'Rote Farbenblindheit.',
    GREEN_EYE: 'Grüne Farbenblindheit.',
    BLUE_EYE: 'Blaue Farbenblindheit.',
    MONO_EYE: 'Rot-, Grün- und Blaublindheit.',
````

**Comment by skerbis** [comment]
@adamchaboryk looks good.

**Comment by skerbis** [comment]
I think this phrases are more common

RED_EYE: 'Rotblindheit',
    GREEN_EYE: 'Grünblindheit',
    BLUE_EYE: 'Blaublindheit',
    MONO_EYE: 'Rot-, Grün- und Blaublindheit.',

**Comment by adamchaboryk** [comment]
Ok perfect, thank you! I'll replace those.

**Pull request closed without merging**
